CREATE TABLE IF NOT EXISTS STYLE (
	ID LONG NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(40) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ARTIST (
    ID LONG NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    STYLE LONG,
    MEMBER LONG,
    RELATED LONG,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PEOPLE (
	ID LONG NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(40) NOT NULL,
	YEARS INTEGER,
	MEMBER LONG,
	PRIMARY KEY (ID),
	CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBER)
	REFERENCES ARTIST(ID)
);

CREATE TABLE IF NOT EXISTS STYLES (
	ID LONG NOT NULL AUTO_INCREMENT,
	ID_ARTIST LONG NOT NULL,
	ID_STYLE LONG NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RELATED (
	ID LONG NOT NULL AUTO_INCREMENT,
	ID_ARTIST LONG NOT NULL,
	ID_ARTIST_RELATED LONG NOT NULL,
	PRIMARY KEY (ID)
);
